trigger: none 

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    arguments: '-PackagesDirectory'
    artifactoryService: 'ecosys'
    targetResolveRepo: 'robi-nuget-virtual'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryNuGet@2
  inputs:
    command: 'push'
    artifactoryService: 'ecosys'
    targetDeployRepo: 'robi-nuget'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'ecosys'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'