trigger: none 

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'ecosys'
    targetResolveRepo: 'robi-nuget-virtual'
    solutionPath: '**/*.sln'
    packagesDirectory: '$(Build.ArtifactStagingDirectory)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\a\1\a\xunit\2.4.1\xunit.2.4.1.nupkg'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\.nupkg'

- task: ArtifactoryNuGet@2
  inputs:
    command: 'push'
    artifactoryService: 'ecosys'
    targetDeployRepo: 'robi-nuget-virtual'
    pathToNupkg: '$(Build.ArtifactStagingDirectory)\*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'ecosys'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'